import type { ReactElement } from 'react';
import { Link } from 'react-router-dom';

export function About(): ReactElement {
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div className="card space-y-3 p-6">
        <h2 className="text-2xl font-semibold text-white">About PyLearn</h2>
        <p className="text-sm text-slate-300">
          PyLearn teaches Python through short, hands-on lessons — multiple choice,
          fill-in-the-blank, and real code you run yourself — with instant, specific feedback
          instead of just "correct" or "incorrect." When you're stuck, hints escalate step by step,
          and you can ask our AI tutor a direct question about exactly what you're looking at.
        </p>
      </div>

      <div className="card space-y-3 p-6">
        <h3 className="text-lg font-semibold text-white">Self-hosted AI, not a paid API</h3>
        <p className="text-sm text-slate-300">
          Hints and chat answers are generated by a small language model we run ourselves — never a
          third-party paid AI service. That model only ever sees the specific lesson content you're
          looking at; it rephrases and elaborates on curated material, it doesn't decide whether
          your answer is correct. Checkpoint grading is always deterministic. If the model is
          unavailable, you still get the lesson's own written hint or explanation — the AI only adds
          to that, it's never required for the app to work.
        </p>
      </div>

      <div className="card space-y-3 p-6">
        <h3 className="text-lg font-semibold text-white">What we store, and where</h3>
        <p className="text-sm text-slate-300">
          If you sign in with Google, your progress (lessons completed, mastery, attempt history) is
          stored on our server so it follows you across devices. If you don't sign in, everything
          stays local to your browser and is never sent anywhere — you can use PyLearn fully
          anonymously. Either way, we don't use your data for anything beyond running the app for
          you.
        </p>
      </div>

      <div className="card space-y-3 p-6">
        <h3 className="text-lg font-semibold text-white">What's next</h3>
        <p className="text-sm text-slate-300">
          PyLearn is early: today there's one curriculum track (Python Basics). Goal-specific tracks
          (automation for DevOps, for networking, and more) are planned but not yet written —
          signing up for a goal now helps us prioritize which one to build first. Spaced-repetition
          review and a native mobile app are on the roadmap too, further out.
        </p>
        <Link to="/onboarding" className="btn btn-primary w-fit">
          Get started
        </Link>
      </div>
    </div>
  );
}
